name: pdf_merge
description: "PDF Merge & Viewer - Gabungkan dan baca banyak file PDF"
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^9.2.2
  flutter_pdfview: ^1.4.1
  pdfrx: ^1.1.2
  pdf: ^3.11.1
  path_provider: ^2.1.6
  path: ^1.9.1
  share_plus: ^11.0.0
  permission_handler: ^11.4.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_logo.png
